name: notas_share
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # files and storage management
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # permissions
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  flutter_slidable: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "images/note_app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/noimage.jpg
